[package]
name = "u4pak"
version = "0.1.0"
authors = ["Mathias Panzenböck <grosser.meister.morti@gmx.net>"]
edition = "2018"
license-file = "LICENSE.txt"

[dependencies]
clap = "2.33.3"
rust-crypto = "^0.2"

[target.'cfg(target_os = "linux")'.dependencies]
# for sendfile() and fuse support
libc = "0.2.94"
