name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Fetch example pak files from submodule
      run: git submodule update --init

    - name: Fuse dependency
      run: sudo apt-get install -y libfuse-dev pkg-config

    - name: Cache pak files
      id: cache-pak
      uses: actions/cache@v2
      with:
        path: |
          pak-examples/pak
        key: ${{ runner.os }}-pak-${{ hashFiles('pak-examples/build/download/*') }}
        restore-keys: |
          ${{ runner.os }}-pak-

    - name: Download pak files
      if: steps.cache-pak.outputs.cache-hit != 'true'
      run: |
        cd pak-examples
        chmod u+x download.sh
        ./download.sh

    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
