name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Fetch example pak files from submodule
      run: git submodule update --init
    - name: Fuse dependency
      run: sudo apt-get install -y libfuse-dev pkg-config
    - name: Download pak files
      run: cd pak-examples && chmod u+x download.sh && ./download.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
